// <auto-generated />
using AvaChocolatier.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvaChocolatier.Migrations
{
    [DbContext(typeof(AvaChocolatierContext))]
    [Migration("20240503143331_NivelBD")]
    partial class NivelBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvaChocolatier.Models.NivelAcesso", b =>
                {
                    b.Property<int>("NivelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NivelID"));

                    b.Property<string>("Acesso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NivelID");

                    b.ToTable("NivelAcesso");
                });
#pragma warning restore 612, 618
        }
    }
}
